version: '3'
services:
  mud:
    container_name: gmud
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile.gmud
    volumes:
    - app:/approot
    environment:
      - WAIT_HOSTS=maria:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "2222:2222"
      - "8081:8081"
    networks:
      - dev
volumes:
  db_data:
  app:
networks:
    dev:
      driver: bridge
